

security.oauth2.client.client-id: trustedclient
security.oauth2.client.client-secret: trustedclient123
security.oauth2.client.authorized-grant-types: authorization_code,refresh_token,password

spring:
  security:
    user:
      name: guest
      password: guest123
